### ISSUE TITLE
Effect is just temporary?

### ISSUE THREAD

**Issue by adams-family** [nriley/brightness#24]
**Environment:**

- MacBook Pro 15" (2018) with TouchBar
- macOS Mojave 10.14.3

**Steps to reproduce:**

1) Installed the latest version via homebrew today.

2) I have an external LG display and a built-in retina display and I want to control by **built-in** display.

3) I issue the following command:

`brightness -d 1 0.5`

The built-in display's brightness changes to 50%

4) In a few seconds (it varies how long) the built-in display's brightness goes back to whatever I adjusted before using the touchbar.

It seems that it always goes back to the exact state I last set up using the standard 'buttons', could it be anywhere between 0 - 100%.

Anyone had the same issue?

**Comment by mafredri** [comment]
While you wait for @nriley to push an official release, you can build it from master, the brew version is outdated.

**Comment by nriley** [comment]
Thanks, @mafredri.

I didn't actually create the homebrew package myself, I just linked to it. If someone else wants to work on getting it to build the most recent version, I am happy to help!

**Comment by adams-family** [comment]
Cool, I can confirm that cloning the latest version from GitHub and compiling it (as stated in the Readme.MD) helped resolve the issue.

**Comment by mafredri** [comment]
@nriley I'm sure if you tag a new release (https://github.com/nriley/brightness/releases), someone will get around to updating the Homebrew package 😄. An official release version is often a prerequisite for things to end up there.

**Comment by mixmastamyk** [comment]
Big Sur.

I just installed this from source and had the same thing happen.  Had to go into the control panel for Displays and deselect "Automatically adust brightness."  While it works, having these two working in concert would be optimal.

**Comment by varenc** [comment]
same problem.  If "Automatically adjust brightness" is enabled, then any changes made with `brightness` are temporary and the system will immediately start gradually adjusting the brightness back to the previous level.  This is unlike the "official" way of changing brightness, which seems to tell macOS to override whatever it thinks the automatically determined brightness should be. 

I assume the fix is finding some other private API call that sending the right signals to the "Automatically adjust brightness" feature.
